### ISSUE TITLE
Desert Russian Army units have bakelite mags instead of black mags

### ISSUE THREAD

**Issue by tova-cup** [tupolov/cfp#104]
The russian standard issue magazine is black since the introduction of the AK-74M (1991).

In CFP however, the desert russians are equipped with Bakelite (brown) magazines.
They should be switched to black magazines to be in line with real life.

Classnames for reference:
`CUP_30Rnd_545x39_AK_M`                  (Bakelite brown magazine)
`CUP_30Rnd_545x39_AK74M_M`          (Polymer black magazine )

 NB: Modern russians are also issued black magazines in CUP.

**Comment by tova-cup** [comment]
Thanks for your reactivity and AUTigerGrad for committing a fix :)

I'd like to point a detail regarding the proposed fix:
The bakelite magazine were replaced by black _plum_ magazines (classname `CUP_30Rnd_545x39_AK74_plum_M`), those magazines however were designed for the AK-74 series of rifles (not the AK-74M) and _are not_ the current standard issue magazines for the russian ground forces.
In fact, they are issued polymer black magazines, the proper classname should be `CUP_30Rnd_545x39_AK74M_M`.

More information on AK magazines : https://www.coolfx.us/ak/ak74_mag_guide_main.htm)

**Comment by AUTigerGrad** [comment]
Will adjust for the next update.
