### ISSUE TITLE
Add YPG faction 

### ISSUE THREAD

**Issue by tupolov** [tupolov/cfp#23]
- [x] Correct Uniform and camo for units
- [x] Custom unit loadouts
- [x] CBA compatibility (EH)
- [x] Units/Vehicles and Weapons/Uniforms in CfgPatches
- [x] RequiredAddons
- [x] Unit insignias
- [x] Element of randomisation
- [x] Full selection of vehicles (incl static weapons)
- [x] Vehicles have gunners where appropriate
- [x] Full set of groups
- [x] Faction Crates / Supplies
- [x] ALiVE Static Data
- [x] Any custom weapons - ACE Compat
- [x] Tested with ALiVE and VCOM
- [x] Localization Stringtables
- [x] Icons and Preview Images
- [x] User Acceptance Test

**Comment by tupolov** [comment]
Needs static weapons and static weapon groups, crates, ALiVE static data and group icons

**Comment by tupolov** [comment]
Needs a flag

**Comment by AUTigerGrad** [comment]
Done
