### ISSUE TITLE
[Request] Change the Western Ultranationalist side to INDFOR

### ISSUE THREAD

**Issue by taro8** [tupolov/cfp#56]
Western Ultranationalist as an OPFOR force don't make that much sense, they would be better suited for and INDFOR faction.
This way they can represent an US militia fighting OPFOR in a Red Dawn-type of a scenario, but they can also act as some insurgents for BLUFOR if needed.
Setting them as an OPFOR faction prevents you for using them as enemy to OPFOR side.
Also, make them speak english (currently they speak russian) and use NATO heads (identityTypes[] = {"LanguageENG_F","Head_NATO","G_GUERIL_default"};)

**Comment by tupolov** [comment]
Done already
