### ISSUE TITLE
CFP_O_IRARMY cannot be used for ALiVE

### ISSUE THREAD

**Issue by xetra11** [tupolov/cfp#79]
**Steps to Reproduce**

- [ ] create empty map i.e. Altis
- [ ] add ALiVE minimum setup
- [ ] Use `CFP_O_IRARMY` for enemy AI Commander
- [ ] Add two Civ Placements (one with filter on huge only and one with small/medium only)
- [ ] Give both Civ Placements the Faction Override with `CFP_O_IRARMY`
- [ ] Start ALiVE mission and observe log and OPCOM/TACOM actions and also Military Logistics

**Expected Behaviour**

- OPCOM is assigning attack objectives (`X` on the Map)
- No Error output in Log regarding `CFP_O_IRARMY`
- Military Logistics working as intended

**Actual Behaviour**

- Log yields: 
```
13:45:23 There are are no groups for OPCOM faction(s) CFP_O_IRARMY! Please ensure you have configured a Mil Placement or Mil Placement (Civ Obj) module for this faction (or faction units are synced to Virtual AI module). If so, please check groups are correctly configured for this faction.
13:45:23 There are are no groups for OPCOM faction(s) ["CFP_O_IRARMY"]! Please check you chose the correct faction(s), and that factions have groups defined in the ArmA 3 default categories infantry, motorized, mechanized, armored, air, sea!
```
- No attacking objectives for the faction coming from ALiVE
- ML is idle as well

**Infos**
- Using `CFP_O_IS` does work fine
- Maybe somethings missing in the faction config (could not figure out since I never touched these)

**Comment by AVESUM** [comment]
I'm using CFP_O_SYARMY,CFP_O_IRARMY and CFP_B_YPG,CUP_B_US_Army respectively and getting the same error. Works as intended with vanilla factions.

**Comment by AUTigerGrad** [comment]
I just tested and all of these factions are spawning correctly in ALiVE.  I'd recommend rechecking your modules.

**Comment by AVESUM** [comment]
Nothing wrong with CFP. Found the error, you can't place more than one faction in a Military Placement Module. Splitted them successfully in two separate modules.

**Comment by AUTigerGrad** [comment]
Fixed
