### ISSUE TITLE
uo_ak_vest.p3d has issues

### ISSUE THREAD

**Issue by tupolov** [tupolov/cfp#81]
14:05:11 Warning: special LOD contains 2nd UV set.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1), Selection r_arm_injury needs a section. The shadow volume may not work well.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1), Selection body_injury needs a section. The shadow volume may not work well.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d: Degenerated triangle found on source triangles (164,426,132)
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d: Degenerated triangle found on source triangles (60,132,426)
14:05:11 Warning: Degenerated faces found in model x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1) 
14:05:11 Warnings in x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1)
14:05:11 Warnings in x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1000)
14:05:11 Warning: special LOD contains 2nd UV set.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1), Selection r_arm_injury needs a section. The shadow volume may not work well.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1), Selection body_injury needs a section. The shadow volume may not work well.
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d: Degenerated triangle found on source triangles (164,426,132)
14:05:11 Warning: x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d: Degenerated triangle found on source triangles (60,132,426)
14:05:11 Warning: Degenerated faces found in model x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1) 
14:05:11 Warnings in x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1)
14:05:11 Warnings in x\cfp\addons\vests\ak_vest\data\model\uo_ak_vest.p3d:shadow(1000)

**Comment by HerrOPS** [comment]
244079fbba8daaa7f70b9d1b236ab800ff5ed8cf ID Fixed

**Comment by HerrOPS** [comment]
244079fbba8daaa7f70b9d1b236ab800ff5ed8cf ID Fixed
