### ISSUE TITLE
alice_sample.p3d has issues

### ISSUE THREAD

**Issue by tupolov** [tupolov/cfp#82]
14:05:58 Warning: Unsupported UVSet 2
14:05:58 Warning: Unsupported UVSet 3
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1597, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1622, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1624, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1642, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1597, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1671, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1672, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1673, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1674, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1675, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1708, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1624, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1672, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1713, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1673, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1714, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1675, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1715, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1718, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1713, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1714, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1719, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1715, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1721, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1722, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1723, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1724, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1725, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1726, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1722, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1727, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1723, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1725, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1728, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1731, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1726, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1727, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1732, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1728, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1622, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1769, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1783, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1642, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1791, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1890, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1915, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1917, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1935, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1890, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1964, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1965, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1966, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1967, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1968, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2001, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1917, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1965, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2006, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1966, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2007, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1968, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2008, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2011, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2006, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2007, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2012, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2008, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2014, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2015, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2016, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2017, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2018, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2019, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2015, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2020, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2016, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2018, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2021, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2024, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2019, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2020, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2025, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2021, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1915, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2062, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2076, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 1935, removed pelvis
14:05:58 Warning: x\cfp\addons\vests\alice\alice_sample.p3d:0, too many bones (more than 4) on vertex 2084, removed pelvis

lots of weighting errors

14:05:59 Warnings in x\cfp\addons\vests\alice\alice_sample.p3d:shadow(1000)

**Comment by HerrOPS** [comment]
The UvSet issue should be resolved.
