### ISSUE TITLE
Various headgear items have bone, weight and geometry issues

### ISSUE THREAD

**Issue by tupolov** [tupolov/cfp#85]
Israeli Mitznefet needs serious help :slightly_smiling_face: lots of issues there
plus the 75th headgear opscores are a little broken
and finally shemagh_full.p3d needs help
oh and lungee_shemagh.p3d :slightly_smiling_face:

**Comment by HerrOPS** [comment]
17:43:16 Warnings in x\cfp\addons\glasses\75neckwear\shemagh_neck_wrap_oakleys.p3d:shadow(1000)

**Comment by AUTigerGrad** [comment]
Fixed in latest release
