### ISSUE TITLE
Support static weapons groups and units

### ISSUE THREAD

**Issue by ampersand38** [tupolov/cfp#88]
`BIS_fnc_packStaticWeapon` requires three personnel in the team: Team Leader, Gunner and Asst. Gunner. Gunner and Asst. Gunner must have `vehicleClass = "MenSupport";`

`BIS_fnc_packStaticWeapon` works with this config patch and adding a leader unit to the group.
[config.cpp.txt](https://github.com/tupolov/cfp/files/3050990/config.cpp.txt)

Vanilla support gunners are inherited through `["B_Soldier_support_base_F","B_Soldier_base_F","SoldierWB","CAManBase","Man","Land","AllVehicles","All"]`. 

I'm guessing it's better to add `vehicleClass = "MenSupport";` to all the support gunners than to mess with the existing inheritance hierarchy?

**Comment by ampersand38** [comment]
Here are all the CfgGroups.hpp with group leaders added.

[cfp.zip](https://github.com/tupolov/cfp/files/3075322/cfp.zip)

**Comment by AUTigerGrad** [comment]
Thank you, fixed in Dev for the next release.
