### ISSUE TITLE
Dynamic Groups with CFP causes lag

### ISSUE THREAD

**Issue by Avokadomos** [tupolov/cfp#93]
Whenever you open the Dynamic Groups window with the U key, the game starts lagging hard. This only happens when CFP is loaded.

To reproduce:
Launch a Zeus scenario or any other with Dynamic Groups. Press U.

Loaded mods:
CBA_A3
CUP Weapons
CUP Units
CUP Vehicles
Community Faction Project

**Comment by Avokadomos** [comment]
It most likely has to do with the insane amount of insignias in the mod. I deleted cfp_insignia.pbo, and it's working fine.

**Comment by AUTigerGrad** [comment]
Fixed in last release with insignia move
