### ISSUE TITLE
Excessive amounts of insignias cause editor attributes lag

### ISSUE THREAD

**Issue by Freddo3000** [tupolov/cfp#96]
Due to having 3859 insignias, whenever you open attributes they all have to load to memory. If you have a HDD, this may take up to five seconds as it has to load ~150 MB of assets, and as Arma doesn't cache these you have to load it each and every time you open unit attributes.

I'd suggest reducing the amount of insignias to less than five per faction at least, preferably around two per faction as this is currently unacceptable. 

Edit: This was tested on a clean install from Steam Workshop, running only CFP and its dependencies. Removing `cfp_insignia.pbo` resolved the issue.

**Comment by Freddo3000** [comment]
Related issue: https://github.com/tupolov/cfp/issues/93

**Comment by AUTigerGrad** [comment]
Fixed in last release.  Majority of insignias moved to options pbo
