### ISSUE TITLE
Error Undefined variable in expression: _helmet

### ISSUE THREAD

**Issue by adampiskorski** [tupolov/cfp#97]
When I place down an AI-controlled man of `B_Pilot_F`, (or 2035 NATO > Men > Pilot)
and any other man to play as (including the same type), I then get the following script error in my log and on screen (since I have `Show Script Errors` enabled), when I start the game and every couple of seconds indefinetely:

```
Error in expression <== "NVGoggles") exitWith {
_nvgHelmet = _helmet;
};
} forEach _helmetSubItems;
}>
Error position: <_helmet;
};
} forEach _helmetSubItems;
}>
Error Undefined variable in expression: _helmet
File x\cfp\addons\main\XEH_postInit.sqf..., line 25
```

**Steps to reproduce:**

1. Create a fresh mission in Virtual Reality terrain
2. Place down any man to be a player
3. Place down 2035 NATO > Men > Pilot
4. Preview and notice the error after a few seconds when the simulation starts.

**Environment:**

- CFP from Steam Workshop (version unknown - doesn't show up in the main menu, but it has steam workshop timestamp of 5248765148746583228 according to the `meta.cpp`)
- Arma 3 Version: 1.96.146114
- CBA V3.13.0
- CUP Weapons 1.13.1
- CUP Units 1.13.0
- CUP Vehicles 1.13.0

**Comment by AUTigerGrad** [comment]
Fixed in Dev
