### ISSUE TITLE
Unit randomization button protection does not seem to function

### ISSUE THREAD

**Issue by ual002** [tupolov/cfp#99]
Certain factions, namely the USARMY Woodland Delta force group units don't seem to retain their changed loadout in BI arsenal after changing it and then reentering BI arsenal. It appears to happen whether or not the 2 checkboxes about alive and CFP randomization are checked in the attributes of the unit. 

Can reproduce with CFP and all dependencies only.

STEPS:
Create any US ARMY Jungle Woodland Delta unit.  
Open attributes and select both Override Alive Orbat and Disable CFP Randomization, save.
Edit unit in BI arsenal.  Change gun. Save
Reopen, watch gun immediately switch back.  Can get around by selecting all the unit equipment slots once.

OPTIONAL:
If ACE and its arsenal are installed, selecting the unit equipment slots does not seem to undo randomization or default reset like with BI arsenal

**Comment by ual002** [comment]
But I think this affects all CFP factions, I only tested a few.

**Comment by ual002** [comment]
I just noticed this does NOT happen with the US ARMY Arid/Desert Delta unit.

**Comment by AUTigerGrad** [comment]
invalid
